[project]
name = "x-particle"
version = "0.1.0"
description = "x-particle is super efficient AI forex trading bot."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "openai-agent>=0.1.0",
    "python-dotenv>=1.2.1",
]
